version: '3'

services:
    server:
        build: ./nginx
        ports:
            - 8080:80
        links:
            - app
    app:
        volumes:
            - ../code/:/var/www
        build: ./php-fpm
        working_dir: /var/www
        links:
            - database
        environment:
            - DB_HOST=database
    
    database:
        image: mysql
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=homestead
            